config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do

  namespace :api, defaults: { format: :json }, path: '/api/' do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do

      #users
      resources :users, :only => [:show, :create, :update, :destroy,:index]

      #questions
      resources :questions, :only => [:create]

      #friendship
      resources :friendships, :only => [:index, :create, :destroy]

      #rooms
      resources :rooms, :only => [:index, :create]

      #room_users
      get 'join_room' => 'room_users#join_room'
      delete 'leave_room' => 'room_users#destroy'
      resources :room_users, :only => [:index]

      #game_cards
      get 'unreceived_cards' => 'game_cards#unreceived_cards'
      resources :game_cards, :only => [:index, :update]

      #categories
      resources :categories, :only => [:index]

      #sessions
      delete '/sessions/logout', to: 'sessions#destroy'
      post '/sessions/login', to: 'sessions#create'


      devise_for :users
    end
  end

  root 'static_pages#home'

  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'dashboard' => 'dashboard#index'

  resources :users
  resources :categories
  resources :questions
  resources :cards
  resources :rooms

end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :category
  has_many :question_in_cards
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < ApplicationController
  def create
    question = Question.new(question_params)
    if question.save
      render json: question, status: 201
    else
      render json: { errors: question.errors }, status: 422
    end
  end

  private
  def question_params
    params.require(:question).permit(:content)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.paginate(:page => params[:page], :per_page => 30)
  end

  def new
    @question = Question.new
    @categories = Category.all.pluck(:name, :id)
  end

  def edit
    @question = Question.find(params[:id])
    @categories = Category.all.pluck(:name, :id)
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      flash[:success] = "Dodano pytanie"
      redirect_to questions_path
    else
      flash[:warning] = "Nie udało się dodać pytania"
      render 'new'
    end
  end

  def update
    @question = Question.find(params[:id])
    if @question.update_attributes(question_params)
      flash[:success] = "Dane zaktualizowane"
      redirect_to questions_path
    else
      render 'edit'
    end
  end

  def destroy
    @question = Question.find(params[:id])
    if @question.confirmed
      @question.confirmed = false
    else
      @question.confirmed = true
    end
    if @question.save
      flash[:success] = "Pomyślnie zmieniono"
      redirect_to questions_path
    else
      flash[:warning] = "Nie udało się zmienić"
      redirect_to questions_path
    end
  end

  private

  def question_params
    params.require(:question).permit(:content, :category_id, :confirmed)
  end

end

app/helpers/api/v1/questions_helper.rb
module Api::V1::QuestionsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_for @question do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <%= f.text_area :content, class: 'form-control', :required => true, :placeholder => "Treść" %>
    <%= f.select :category_id, options_for_select(@categories, @question.category_id), {:include_blank => "Kategoria"}, {:class => "form-control"} %>
    <%= f.hidden_field :confirmed, :value => true %>

    <%= f.submit "Zapisz", :class => "btn btn-danger btn-lg btn-block" %>

<% end %>

app/views/questions/_question.html.erb
<tr>
  <td><%= question.content %></td>
  <td>
    <% if question.confirmed %>
        <img src="http://www.vi-decals.com/ocart/image/correct.png" width="25" height="25">
    <% else %>
        <img src="http://www.ratedartisan.com/images/delete1.png" width="25" height="25">
    <% end %>
  </td>
  <td class="table_buttons">
    <%= link_to "<i class='fa fa-pencil fa-2x'></i>".html_safe, edit_question_path(question) %>
    <% if question.confirmed %>
        <%= link_to "<i class='fa fa-ban fa-2x'></i>".html_safe, question, method: :delete %>
    <% else %>
        <%= link_to "<i class='fa fa-check fa-2x'></i>".html_safe, question, method: :delete %>
    <% end %>
  </td>
</tr>

app/views/questions/edit.html.erb
<div class="row">
  <div class="col-lg-12">
    <h2>Edytuj pytanie</h2>
  </div>
</div>
<!-- /. ROW  -->
<hr/>
<!-- /. ROW  -->
<div class="row text-center pad-top">
  <div class="col-lg-12">
    <%= render 'form' %>
  </div>
</div>

app/views/questions/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <h2>Lista pytań w systemie</h2>
  </div>
</div>
<!-- /. ROW  -->
<hr/>
<!-- /. ROW  -->
<div class="row text-center pad-top">
  <div class="col-lg-12">
    <div class="table-responsive">
      <%= will_paginate @questions, :previous_label => t("Poprzednie"), :next_label => t("Następne") %>
      <table class="table table-striped">
        <thead>
        <tr>
          <th>Treść</th>
          <th>Zatwierdzone</th>
          <th></th>
        </tr>
        </thead>
        <tbody>
        <%= render @questions %>
        </tbody>
      </table>
      <%= will_paginate @questions, :previous_label => t("Poprzednie"), :next_label => t("Następne") %>
    </div>
    <div class="row">
      <div class="col-md-12">
        <%= link_to "Dodaj nowe pytanie", new_question_path, :class => "btn btn-danger btn-lg btn-block" %>
      </div>
    </div>
  </div>
</div>

app/views/questions/new.html.erb
<div class="row">
  <div class="col-lg-12">
    <h2>Nowe pytanie</h2>
  </div>
</div>
<!-- /. ROW  -->
<hr/>
<!-- /. ROW  -->
<div class="row text-center pad-top">
  <div class="col-lg-12">
    <%= render 'form' %>
  </div>
</div>