config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do

  namespace :api, defaults: { format: :json }, path: '/api/' do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do

      #users
      resources :users, :only => [:show, :create, :update, :destroy,:index]

      #questions
      resources :questions, :only => [:create]

      #friendship
      resources :friendships, :only => [:index, :create, :destroy]

      #rooms
      resources :rooms, :only => [:index, :create]

      #room_users
      get 'join_room' => 'room_users#join_room'
      delete 'leave_room' => 'room_users#destroy'
      resources :room_users, :only => [:index]

      #game_cards
      get 'unreceived_cards' => 'game_cards#unreceived_cards'
      resources :game_cards, :only => [:index, :update]

      #categories
      resources :categories, :only => [:index]

      #sessions
      delete '/sessions/logout', to: 'sessions#destroy'
      post '/sessions/login', to: 'sessions#create'


      devise_for :users
    end
  end

  root 'static_pages#home'

  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'dashboard' => 'dashboard#index'

  resources :users
  resources :categories
  resources :questions
  resources :cards
  resources :rooms

end

app/models/room.rb
class Room < ActiveRecord::Base
  has_many :room_users
  belongs_to :category
end

app/controllers/api/v1/rooms_controller.rb
class Api::V1::RoomsController < ApplicationController
  respond_to :json
  before_action :authenticate_with_token!, only: [:index]

  def index
    rooms = Room.all
    render json: rooms, status: 200
  end

  def create
    room = Room.create(room_params);
    room.category_id = Category.all.sample.id
    if room.save
      render json: room, status: 201
    else
      render json: { errors: room.errors }, status: 422
    end
  end

  private

  def room_params
    params.require(:room).permit(:name)
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = Room.paginate(:page => params[:page], :per_page => 15)
  end

  def show
    @room = Room.find(params[:id])
    @users = @room.room_users
  end

  def new
    @room = Room.new
    @categories = Category.all.pluck(:name, :id)
  end

  def edit
    @room = Room.find(params[:id])
    @categories = Category.all.pluck(:name, :id)
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      flash[:success] = "Dodano pokój"
      redirect_to rooms_path
    else
      flash[:warning] = "Nie udało się dodać pokoju"
      render 'new'
    end
  end

  def update
    @room = Room.find(params[:id])
    if @room.update_attributes(room_params)
      flash[:success] = "Dane zaktualizowane"
      redirect_to rooms_path
    else
      render 'edit'
    end
  end

  def destroy
    @room = Room.find(params[:id]).destroy
    flash[:success] = "Usunięto pokój"
    redirect_to rooms_path
  end

  private

  def room_params
    params.require(:room).permit(:name, :category_id)
  end
end

app/helpers/api/v1/rooms_helper.rb
module Api::V1::RoomsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_for @room do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <%= f.text_field :name, class: 'form-control', :required => true, :placeholder => "Nazwa" %>
    <%= f.select :category_id, options_for_select(@categories, @room.category_id), {:include_blank => "Kategoria"}, {:class => "form-control"} %>

    <%= f.submit "Zapisz", :class => "btn btn-danger btn-lg btn-block" %>

<% end %>

app/views/rooms/_room.html.erb
<tr>
  <td><%= room.name %></td>
  <td>
    <%= room.category.name %>
  </td>
  <td>
    <%= room.room_users.count %>
  </td>
  <td class="table_buttons">
    <%= link_to "<i class='fa fa-eye fa-2x'></i>".html_safe, room %>
    <%= link_to "<i class='fa fa-pencil fa-2x'></i>".html_safe, edit_room_path(room) %>
    <%= link_to "<i class='fa fa-trash fa-2x'></i>".html_safe, room, method: :delete %>
  </td>
</tr>

app/views/rooms/_room_user.html.erb
<tr>
  <td><%= room_user.user.login %></td>
  <td>
    <%= room_user.user.email %>
  </td>
</tr>

app/views/rooms/edit.html.erb
<div class="row">
  <div class="col-lg-12">
    <h2>Edytuj pokój</h2>
  </div>
</div>
<!-- /. ROW  -->
<hr/>
<!-- /. ROW  -->
<div class="row text-center pad-top">
  <div class="col-lg-12">
    <%= render 'form' %>
  </div>
</div>

app/views/rooms/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <h2>Lista pokoi</h2>
  </div>
</div>
<!-- /. ROW  -->
<hr/>
<!-- /. ROW  -->
<div class="row text-center pad-top">
  <div class="col-lg-12">
    <div class="table-responsive">
      <%= will_paginate @rooms, :previous_label => t("Poprzednie"), :next_label => t("Następne") %>
      <table class="table table-striped">
        <thead>
        <tr>
          <th>Nazwa</th>
          <th>Kategoria</th>
          <th>Liczba graczy</th>
          <th></th>
        </tr>
        </thead>
        <tbody>
        <%= render @rooms %>
        </tbody>
      </table>
      <%= will_paginate @rooms, :previous_label => t("Poprzednie"), :next_label => t("Następne") %>
    </div>
    <div class="row">
      <div class="col-md-12">
        <%= link_to "Dodaj nowy pokój", new_room_path, :class => "btn btn-danger btn-lg btn-block" %>
      </div>
    </div>
  </div>
</div>

app/views/rooms/new.html.erb
<div class="row">
  <div class="col-lg-12">
    <h2>Dodaj pokój</h2>
  </div>
</div>
<!-- /. ROW  -->
<hr/>
<!-- /. ROW  -->
<div class="row text-center pad-top">
  <div class="col-lg-12">
    <%= render 'form' %>
  </div>
</div>

app/views/rooms/show.html.erb
<div class="row">
  <div class="col-lg-12">
    <h2>Lista użytkowników</h2>
  </div>
</div>
<!-- /. ROW  -->
<hr/>
<!-- /. ROW  -->
<div class="row text-center pad-top">
  <div class="col-lg-12">
    <div class="table-responsive">
      <table class="table table-striped">
        <thead>
        <tr>
          <th>Login</th>
          <th>Email</th>
        </tr>
        </thead>
        <tbody>
        <% @users.each do |user| %>
            <%= render 'rooms/room_user', room_user: user %>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>