config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do

  namespace :api, defaults: { format: :json }, path: '/api/' do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do

      #users
      resources :users, :only => [:show, :create, :update, :destroy,:index]

      #questions
      resources :questions, :only => [:create]

      #friendship
      resources :friendships, :only => [:index, :create, :destroy]

      #rooms
      resources :rooms, :only => [:index, :create]

      #room_users
      get 'join_room' => 'room_users#join_room'
      delete 'leave_room' => 'room_users#destroy'
      resources :room_users, :only => [:index]

      #game_cards
      get 'unreceived_cards' => 'game_cards#unreceived_cards'
      resources :game_cards, :only => [:index, :update]

      #categories
      resources :categories, :only => [:index]

      #sessions
      delete '/sessions/logout', to: 'sessions#destroy'
      post '/sessions/login', to: 'sessions#create'


      devise_for :users
    end
  end

  root 'static_pages#home'

  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'dashboard' => 'dashboard#index'

  resources :users
  resources :categories
  resources :questions
  resources :cards
  resources :rooms

end

app/models/card.rb
class Card < ActiveRecord::Base
  has_many :question_in_cards, dependent: :destroy

  accepts_nested_attributes_for :question_in_cards, :allow_destroy => true
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :questions
  has_many :cards
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
end

app/models/game_card.rb
class GameCard < ActiveRecord::Base
  belongs_to :room_user
  belongs_to :card
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :category
  has_many :question_in_cards
end

app/models/question_in_card.rb
class QuestionInCard < ActiveRecord::Base
  belongs_to :card
  belongs_to :question
end

app/models/room.rb
class Room < ActiveRecord::Base
  has_many :room_users
  belongs_to :category
end

app/models/room_user.rb
class RoomUser < ActiveRecord::Base
  belongs_to :room
  belongs_to :user
  has_many :game_cards
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :friendships
  has_many :room_users
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :auth_token, uniqueness: true

  before_create :generate_authentication_token!

  def generate_authentication_token!
    begin
      self.auth_token = Devise.friendly_token
    end while self.class.exists?(auth_token: auth_token)
  end

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
        BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  #Update attribute remember_digest to true.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Returns true if the given token matches the digest.
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

  # Sets the password reset attributes.
  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest,  User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  # Sends password reset email.
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  # Returns true if a password reset has expired.
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  private

  # Converts email to all lower-case.
  def downcase_email
    self.email = email.downcase
  end

  # Creates and assigns the activation token and digest.
  def create_activation_digest
    self.activation_token  = User.new_token
    self.activation_digest = User.digest(activation_token)
  end


end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/front_helper.rb
module FrontHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # Returns the user corresponding to the remember token cookie.
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(:remember, cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Forgets a persistent session.
  def forget(user)
    #user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # Logs out the current user.
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_side_nav.html.erb
<nav class="navbar-default navbar-side" role="navigation">
  <div class="sidebar-collapse">
    <ul class="nav" id="main-menu">



      <li class="active-link">
        <%= link_to dashboard_path do%><i class="fa fa-tachometer"></i>Dashboard<% end %>
      </li>

      <li>
        <%= link_to users_path do%><i class="fa fa-users"></i>Lista użytkowników<% end %>
      </li>
      <li>
        <%= link_to questions_path do%><i class="fa fa-question-circle"></i>Lista pytań<% end %>
      </li>
      <li>
        <%= link_to new_question_path do%><i class="fa fa-question-circle-o"></i>Dodaj pytanie<% end %>
      </li>


      <li>
        <%= link_to categories_path do%><i class="fa fa-list-alt"></i>Lista kategorii pytań<% end %>
      </li>
      <li>
        <%= link_to new_category_path do%><i class="fa fa-plus"></i>Dodaj kategorię<% end %>
      </li>

      <li>
        <%= link_to cards_path do%><i class="fa fa-comments"></i>Lista kart<% end %>
      </li>
      <li>
        <%= link_to new_card_path do%><i class="fa fa-comment"></i>Dodaj kartę<% end %>
      </li>

      <li>
        <%= link_to rooms_path do%><i class="fa fa-gamepad"></i>Lista pokoi<% end %>
      </li>
      <li>
        <%= link_to new_room_path do%><i class="fa fa-plus-square-o"></i>Dodaj pokój<% end %>
      </li>

    </ul>
  </div>

</nav>

app/views/layouts/_top_nav.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="adjust-nav">

                <span class="logout-spn" >
                  <%= link_to logout_path, method: "delete" do%><i class="fa fa-sign-out fa-fw fa-2x"></i> <% end %>

                </span>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>Sema Admin</title>
  <link rel='stylesheet prefetch' href='http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css'>
  <%= stylesheet_link_tag 'dashboard', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'/>
</head>
<body>
<div id="wrapper">
  <%= render "layouts/top_nav" %>
  <%= render "layouts/side_nav" %>
  <div id="page-wrapper">
    <div id="page-inner">
      <%= yield %>
    </div>
    <!-- /. PAGE INNER  -->
  </div>
</div>


<!-- /. WRAPPER  -->
<!-- SCRIPTS -AT THE BOTOM TO REDUCE THE LOAD TIME-->
<!-- JQUERY SCRIPTS -->
<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.2/jquery-ui.js"></script>
<script src="js/custom.js"></script>


</body>
</html>

app/views/shared/_error_messages.html.erb
<% if !@user.nil? %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        The form contains <%= pluralize(@user.errors.count, "error") %>.
      </div>
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<% end %>